### ISSUE TITLE
Type definition error with Typescript

### ISSUE THREAD

**Issue by drashtipatoliya17** [grid-js/gridjs-angular#159] opened 2021-07-12 07:14 UTC
I am trying to use the plugin with latest version of angular with Typescript and getting following issue. I have gone through the documentation and everything, but not able to figure out any solution. It seems, there is some issue with type declaration in the probably core plugin.

```
Error: node_modules/gridjs/dist/src/view/base.d.ts:5:67 - error TS2344: Type 'unknown' does not satisfy the constraint 'BaseProps'.

5 export declare abstract class BaseComponent<P extends BaseProps = unknown, S = unknown> extends Component<P, S> {


```

Feel free to close this, if it's not an real issue.

**Environments:**

- Angular: 12.0.1
- TypeScript: 4.2.3
- GridJS: 5.0.2
- gridjs-angular: 1.2.0

**Comment by jdesignermayor** [comment] 2021-10-27 21:40
i have the same problem!!

**Comment by salamaashoush** [comment] 2024-02-01 22:26
I am working on publishing a new version to fix this soon, I will close this one since it is a duplicate of this https://github.com/grid-js/gridjs-angular/issues/180

**Closed as completed by salamaashoush** 2024-02-01 22:26 UTC
